import Foundation

/// File paths for a single model entry in a KittenTTS bundled-assets manifest.
public struct KittenTTSBundledModelFiles: Sendable, Decodable, Equatable {
    public let onnx: String
    public let voices: String

    public init(onnx: String, voices: String) {
        self.onnx = onnx
        self.voices = voices
    }
}

/// Shared phonemizer paths from a KittenTTS bundled-assets manifest.
public struct KittenTTSBundledPhonemizerFiles: Sendable, Decodable, Equatable {
    public let phonemizerRules: String
    public let phonemizerList: String

    public init(phonemizerRules: String, phonemizerList: String) {
        self.phonemizerRules = phonemizerRules
        self.phonemizerList = phonemizerList
    }
}

/// Manifest generated by `kittentts-react-native bundle-assets`.
public struct KittenTTSBundledAssetsManifest: Sendable, Decodable, Equatable {
    public let version: Int
    public let defaultModel: KittenModel
    public let models: [KittenModel: KittenTTSBundledModelFiles]
    public let files: KittenTTSBundledPhonemizerFiles

    public var availableModels: [KittenModel] {
        Array(models.keys).sorted { $0.rawValue < $1.rawValue }
    }

    public func modelFiles(for model: KittenModel? = nil) throws -> KittenTTSBundledModelFiles {
        let selectedModel = model ?? defaultModel
        guard let files = models[selectedModel] else {
            throw KittenTTSError.invalidModelData(
                "Model \(selectedModel.rawValue) is not present in bundled assets manifest."
            )
        }
        return files
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        version = try container.decode(Int.self, forKey: .version)
        files = try container.decode(KittenTTSBundledPhonemizerFiles.self, forKey: .files)

        switch version {
        case 1:
            let model = try Self.decodeModel(from: container, forKey: .model)
            let modelFiles = try container.decode(KittenTTSBundledModelFiles.self, forKey: .files)
            defaultModel = model
            models = [model: modelFiles]

        case 2:
            defaultModel = try Self.decodeModel(from: container, forKey: .defaultModel)
            let rawModels = try container.decode(
                [String: KittenTTSBundledModelFiles].self,
                forKey: .models
            )
            models = try Dictionary(uniqueKeysWithValues: rawModels.map { key, value in
                guard let model = KittenModel(id: key) else {
                    throw KittenTTSError.invalidModelData(
                        "Unknown KittenTTS model in bundled assets manifest: \(key)"
                    )
                }
                return (model, value)
            })

        default:
            throw KittenTTSError.invalidModelData(
                "Unsupported bundled assets manifest version: \(version)"
            )
        }

        guard models[defaultModel] != nil else {
            throw KittenTTSError.invalidModelData(
                "Default model \(defaultModel.rawValue) is not present in bundled assets manifest."
            )
        }
    }

    private enum CodingKeys: String, CodingKey {
        case version
        case model
        case defaultModel
        case models
        case files
    }

    private static func decodeModel(
        from container: KeyedDecodingContainer<CodingKeys>,
        forKey key: CodingKeys
    ) throws -> KittenModel {
        let rawValue = try container.decode(String.self, forKey: key)
        guard let model = KittenModel(id: rawValue) else {
            throw KittenTTSError.invalidModelData(
                "Unknown KittenTTS model in bundled assets manifest: \(rawValue)"
            )
        }
        return model
    }
}

/// Helpers for constructing a ``KittenTTSConfig`` from bundled offline assets.
public enum KittenTTSBundledAssets {

    /// Decode a manifest generated by the React Native SDK asset bundler.
    public static func loadManifest(from manifestURL: URL) throws -> KittenTTSBundledAssetsManifest {
        let data = try Data(contentsOf: manifestURL)
        return try JSONDecoder().decode(KittenTTSBundledAssetsManifest.self, from: data)
    }

    /// Create a config from a decoded manifest and the directory containing its files.
    public static func config(
        from manifest: KittenTTSBundledAssetsManifest,
        baseURL: URL,
        model: KittenModel? = nil,
        defaultVoice: KittenVoice = .bella,
        speed: Float = 1.0,
        storageDirectory: URL? = nil,
        ortNumThreads: Int = 4,
        maxTokensPerChunk: Int = 400
    ) throws -> KittenTTSConfig {
        let selectedModel = model ?? manifest.defaultModel
        let modelFiles = try manifest.modelFiles(for: selectedModel)

        return KittenTTSConfig(
            model: selectedModel,
            defaultVoice: defaultVoice,
            speed: speed,
            phonemizer: .custom(EPhonemizer(
                rulesFileURL: baseURL.appendingPathComponent(manifest.files.phonemizerRules),
                listFileURL: baseURL.appendingPathComponent(manifest.files.phonemizerList)
            )),
            storageDirectory: storageDirectory,
            modelFiles: KittenTTSModelFiles(
                onnxURL: baseURL.appendingPathComponent(modelFiles.onnx),
                voicesURL: baseURL.appendingPathComponent(modelFiles.voices)
            ),
            ortNumThreads: ortNumThreads,
            maxTokensPerChunk: maxTokensPerChunk
        )
    }

    /// Create a config from bundled app resources.
    ///
    /// The React Native Expo config plugin copies assets into a `kittentts`
    /// folder resource, so the default `assetRoot` matches that layout.
    public static func configFromBundle(
        _ bundle: Bundle = .main,
        assetRoot: String = "kittentts",
        model: KittenModel? = nil,
        defaultVoice: KittenVoice = .bella,
        speed: Float = 1.0,
        storageDirectory: URL? = nil,
        ortNumThreads: Int = 4,
        maxTokensPerChunk: Int = 400
    ) throws -> KittenTTSConfig {
        guard let manifestURL = bundle.url(
            forResource: "manifest",
            withExtension: "json",
            subdirectory: assetRoot
        ) else {
            throw KittenTTSError.invalidModelData(
                "Bundled assets manifest not found in bundle subdirectory '\(assetRoot)'."
            )
        }

        let manifest = try loadManifest(from: manifestURL)
        return try config(
            from: manifest,
            baseURL: manifestURL.deletingLastPathComponent(),
            model: model,
            defaultVoice: defaultVoice,
            speed: speed,
            storageDirectory: storageDirectory,
            ortNumThreads: ortNumThreads,
            maxTokensPerChunk: maxTokensPerChunk
        )
    }
}
